top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/server/mpm/event
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/server/mpm/event
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/server/mpm/event
include $(top_srcdir)/build/special.mk
