top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/filters
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/filters
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/filters

include $(top_srcdir)/build/special.mk

