top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/server/mpm
builddir     = /home/yigonghu/software/httpd/apache/server/mpm
VPATH        = /home/yigonghu/software/httpd/apache/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
