top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/server/mpm
builddir     = /home/yigonghu/software/httpd/2.4.38/server/mpm
VPATH        = /home/yigonghu/software/httpd/2.4.38/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
