top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/mappers
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/mappers
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/mappers

include $(top_srcdir)/build/special.mk

