top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/arch/unix
builddir     = /home/yigonghu/software/httpd/apache/modules/arch/unix
VPATH        = /home/yigonghu/software/httpd/apache/modules/arch/unix

include $(top_srcdir)/build/special.mk

