top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/loggers
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/loggers
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/loggers

include $(top_srcdir)/build/special.mk

