top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/loggers
builddir     = /home/yigonghu/software/httpd/apache/modules/loggers
VPATH        = /home/yigonghu/software/httpd/apache/modules/loggers

include $(top_srcdir)/build/special.mk

