top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/aaa
builddir     = /home/yigonghu/software/httpd/apache/modules/aaa
VPATH        = /home/yigonghu/software/httpd/apache/modules/aaa

include $(top_srcdir)/build/special.mk

