top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/aaa
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/aaa
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/aaa

include $(top_srcdir)/build/special.mk

