top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/os/unix
builddir     = /home/yigonghu/software/httpd/apache/os/unix
VPATH        = /home/yigonghu/software/httpd/apache/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
