top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/echo
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/echo
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/echo

include $(top_srcdir)/build/special.mk

