top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/generators
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/generators
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/generators

include $(top_srcdir)/build/special.mk

