top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/generators
builddir     = /home/yigonghu/software/httpd/apache/modules/generators
VPATH        = /home/yigonghu/software/httpd/apache/modules/generators

include $(top_srcdir)/build/special.mk

