top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/core
builddir     = /home/yigonghu/software/httpd/apache/modules/core
VPATH        = /home/yigonghu/software/httpd/apache/modules/core

include $(top_srcdir)/build/special.mk

