top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/lua
builddir     = /home/yigonghu/software/httpd/apache/modules/lua
VPATH        = /home/yigonghu/software/httpd/apache/modules/lua
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
