top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/arch/unix
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/arch/unix
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/arch/unix

include $(top_srcdir)/build/special.mk

