top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/echo
builddir     = /home/yigonghu/software/httpd/apache/modules/echo
VPATH        = /home/yigonghu/software/httpd/apache/modules/echo

include $(top_srcdir)/build/special.mk

