top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/proxy
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/proxy
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/proxy
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
#SUBDIRS = balancers
include $(top_srcdir)/build/special.mk
