top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/cache
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/cache
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/cache

include $(top_srcdir)/build/special.mk

