top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/os
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/os
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
