top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/mappers
builddir     = /home/yigonghu/software/httpd/apache/modules/mappers
VPATH        = /home/yigonghu/software/httpd/apache/modules/mappers

include $(top_srcdir)/build/special.mk

