top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/mappers
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/mappers
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/mappers

include $(top_srcdir)/build/special.mk

