top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/filters
builddir     = /home/yigonghu/software/httpd/apache/modules/filters
VPATH        = /home/yigonghu/software/httpd/apache/modules/filters

include $(top_srcdir)/build/special.mk

