top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/metadata
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/metadata
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/metadata

include $(top_srcdir)/build/special.mk

