top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/metadata
builddir     = /home/yigonghu/software/httpd/apache/modules/metadata
VPATH        = /home/yigonghu/software/httpd/apache/modules/metadata

include $(top_srcdir)/build/special.mk

