top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/os
builddir     = /home/yigonghu/software/httpd/2.4.38/os
VPATH        = /home/yigonghu/software/httpd/2.4.38/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
