top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/os
builddir     = /home/yigonghu/software/httpd/apache/os
VPATH        = /home/yigonghu/software/httpd/apache/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
