top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/http
builddir     = /home/yigonghu/software/httpd/apache/modules/http
VPATH        = /home/yigonghu/software/httpd/apache/modules/http

include $(top_srcdir)/build/special.mk

