top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/http
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/http
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/http

include $(top_srcdir)/build/special.mk

