top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/echo
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/echo
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/echo

include $(top_srcdir)/build/special.mk

