top_srcdir   = /home/chandy/project/psandbox/apache/httpd-2.4.38
top_builddir = /home/chandy/project/psandbox/apache/httpd-2.4.38
srcdir       = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/dav/main
builddir     = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/dav/main
VPATH        = /home/chandy/project/psandbox/apache/httpd-2.4.38/modules/dav/main
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
