top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/modules/cache
builddir     = /home/yigonghu/software/httpd/apache/modules/cache
VPATH        = /home/yigonghu/software/httpd/apache/modules/cache

include $(top_srcdir)/build/special.mk

