top_srcdir   = /home/yigonghu/software/httpd/apache
top_builddir = /home/yigonghu/software/httpd/apache
srcdir       = /home/yigonghu/software/httpd/apache/server/mpm/prefork
builddir     = /home/yigonghu/software/httpd/apache/server/mpm/prefork
VPATH        = /home/yigonghu/software/httpd/apache/server/mpm/prefork
include $(top_srcdir)/build/special.mk
