top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/server/mpm/prefork
builddir     = /home/yigonghu/software/httpd/2.4.38/server/mpm/prefork
VPATH        = /home/yigonghu/software/httpd/2.4.38/server/mpm/prefork
include $(top_srcdir)/build/special.mk
