top_srcdir   = /home/yigonghu/software/httpd/2.4.38
top_builddir = /home/yigonghu/software/httpd/2.4.38
srcdir       = /home/yigonghu/software/httpd/2.4.38/modules/core
builddir     = /home/yigonghu/software/httpd/2.4.38/modules/core
VPATH        = /home/yigonghu/software/httpd/2.4.38/modules/core

include $(top_srcdir)/build/special.mk

